import {
  AccessTime20Filled,
  AccessTime20Regular,
  Accessibility20Filled,
  Accessibility20Regular,
  Agents20Filled,
  Agents20Regular,
  Airplane20Filled,
  Airplane20Regular,
  Alert20Filled,
  Alert20Regular,
  ApprovalsApp20Filled,
  ApprovalsApp20Regular,
  Apps20Filled,
  Apps20Regular,
  AppsListDetail20Filled,
  AppsListDetail20Regular,
  Archive20Filled,
  Archive20Regular,
  ArchiveMultiple20Filled,
  ArchiveMultiple20Regular,
  ArrowSync20Filled,
  ArrowSync20Regular,
  Attach20Filled,
  Attach20Regular,
  Backpack20Filled,
  Backpack20Regular,
  Badge20Filled,
  Badge20Regular,
  BarcodeScanner20Filled,
  BarcodeScanner20Regular,
  Beaker20Filled,
  Beaker20Regular,
  Board20Filled,
  Board20Regular,
  BookDatabase20Filled,
  BookDatabase20Regular,
  BookOpen20Filled,
  BookOpen20Regular,
  BookSearch20Filled,
  BookSearch20Regular,
  Bookmark20Filled,
  Bookmark20Regular,
  Bot20Filled,
  Bot20Regular,
  BotSparkle20Filled,
  BotSparkle20Regular,
  Box20Filled,
  Box20Regular,
  BoxCheckmark20Filled,
  BoxCheckmark20Regular,
  BoxMultiple20Filled,
  BoxMultiple20Regular,
  Brain20Filled,
  Brain20Regular,
  BrainCircuit20Filled,
  BrainCircuit20Regular,
  Branch20Filled,
  Branch20Regular,
  BranchCompare20Filled,
  BranchCompare20Regular,
  Briefcase20Filled,
  Briefcase20Regular,
  Building20Filled,
  Building20Regular,
  BuildingBank20Filled,
  BuildingBank20Regular,
  BuildingFactory20Filled,
  BuildingFactory20Regular,
  BuildingGovernment20Filled,
  BuildingGovernment20Regular,
  BuildingMultiple20Filled,
  BuildingMultiple20Regular,
  Calendar20Filled,
  Calendar20Regular,
  CalendarCheckmark20Filled,
  CalendarCheckmark20Regular,
  Camera20Filled,
  Camera20Regular,
  Certificate20Filled,
  Certificate20Regular,
  ChartMultiple20Filled,
  ChartMultiple20Regular,
  ChatBubblesQuestion20Filled,
  ChatBubblesQuestion20Regular,
  ChatCheckmark20Filled,
  ChatCheckmark20Regular,
  ChatMultiple20Filled,
  ChatMultiple20Regular,
  CheckmarkCircle20Filled,
  CheckmarkCircle20Regular,
  City20Filled,
  City20Regular,
  Classification20Filled,
  Classification20Regular,
  ClipboardCheckmark20Filled,
  ClipboardCheckmark20Regular,
  ClipboardDataBar20Filled,
  ClipboardDataBar20Regular,
  ClipboardEdit20Filled,
  ClipboardEdit20Regular,
  ClipboardError20Filled,
  ClipboardError20Regular,
  ClipboardSearch20Filled,
  ClipboardSearch20Regular,
  ClipboardTask20Filled,
  ClipboardTask20Regular,
  Clock20Filled,
  Clock20Regular,
  Cloud20Filled,
  Cloud20Regular,
  CloudDatabase20Filled,
  CloudDatabase20Regular,
  CloudFlow20Filled,
  CloudFlow20Regular,
  Code20Filled,
  Code20Regular,
  CommentMultiple20Filled,
  CommentMultiple20Regular,
  CompassNorthwest20Filled,
  CompassNorthwest20Regular,
  ContactCard20Filled,
  ContactCard20Regular,
  Crown20Filled,
  Crown20Regular,
  Cube20Filled,
  Cube20Regular,
  DataPie20Filled,
  DataPie20Regular,
  DataTrending20Filled,
  DataTrending20Regular,
  Database20Filled,
  Database20Regular,
  DatabaseSearch20Filled,
  DatabaseSearch20Regular,
  Desk20Filled,
  Desk20Regular,
  Desktop20Filled,
  Desktop20Regular,
  DeveloperBoard20Filled,
  DeveloperBoard20Regular,
  Diagram20Filled,
  Diagram20Regular,
  Doctor20Filled,
  Doctor20Regular,
  Document20Filled,
  Document20Regular,
  DocumentBriefcase20Filled,
  DocumentBriefcase20Regular,
  DocumentCheckmark20Filled,
  DocumentCheckmark20Regular,
  DocumentData20Filled,
  DocumentData20Regular,
  DocumentEdit20Filled,
  DocumentEdit20Regular,
  DocumentFolder20Filled,
  DocumentFolder20Regular,
  DocumentMultiple20Filled,
  DocumentMultiple20Regular,
  DocumentPdf20Filled,
  DocumentPdf20Regular,
  DocumentRibbon20Filled,
  DocumentRibbon20Regular,
  DocumentSearch20Filled,
  DocumentSearch20Regular,
  DocumentSignature20Filled,
  DocumentSignature20Regular,
  DocumentTable20Filled,
  DocumentTable20Regular,
  DocumentText20Filled,
  DocumentText20Regular,
  DocumentWord20Filled,
  DocumentWord20Regular,
  Drawer20Filled,
  Drawer20Regular,
  Earth20Filled,
  Earth20Regular,
  Edit20Filled,
  Edit20Regular,
  Eye20Filled,
  Eye20Regular,
  Filter20Filled,
  Filter20Regular,
  Flag20Filled,
  Flag20Regular,
  Flash20Filled,
  Flash20Regular,
  Flow20Filled,
  Flow20Regular,
  Flowchart20Filled,
  Flowchart20Regular,
  FolderBriefcase20Filled,
  FolderBriefcase20Regular,
  FolderDataBar20Filled,
  FolderDataBar20Regular,
  FolderDocument20Filled,
  FolderDocument20Regular,
  FolderGlobe20Filled,
  FolderGlobe20Regular,
  FolderMultiple20Filled,
  FolderMultiple20Regular,
  FolderOpen20Filled,
  FolderOpen20Regular,
  FolderSearch20Filled,
  FolderSearch20Regular,
  FolderSync20Filled,
  FolderSync20Regular,
  FormMultiple20Filled,
  FormMultiple20Regular,
  Gauge20Filled,
  Gauge20Regular,
  Gavel20Filled,
  Gavel20Regular,
  Gift20Filled,
  Gift20Regular,
  Globe20Filled,
  Globe20Regular,
  Handshake20Filled,
  Handshake20Regular,
  Heart20Filled,
  Heart20Regular,
  History20Filled,
  History20Regular,
  Home20Filled,
  Home20Regular,
  Image20Filled,
  Image20Regular,
  Info20Filled,
  Info20Regular,
  Key20Filled,
  Key20Regular,
  Laptop20Filled,
  Laptop20Regular,
  Layer20Filled,
  Layer20Regular,
  Library20Filled,
  Library20Regular,
  Lightbulb20Filled,
  Lightbulb20Regular,
  Location20Filled,
  Location20Regular,
  LockClosed20Filled,
  LockClosed20Regular,
  Mail20Filled,
  Mail20Regular,
  Map20Filled,
  Map20Regular,
  Microscope20Filled,
  Microscope20Regular,
  Money20Filled,
  Money20Regular,
  MoreHorizontal20Filled,
  MoreHorizontal20Regular,
  Navigation20Filled,
  Navigation20Regular,
  News20Filled,
  News20Regular,
  Notebook20Filled,
  Notebook20Regular,
  Notepad20Filled,
  Notepad20Regular,
  Organization20Filled,
  Organization20Regular,
  PanelLeft20Filled,
  PanelLeft20Regular,
  Patient20Filled,
  Patient20Regular,
  Pen20Filled,
  Pen20Regular,
  People20Filled,
  People20Regular,
  PeopleCommunity20Filled,
  PeopleCommunity20Regular,
  PeopleTeam20Filled,
  PeopleTeam20Regular,
  PeopleTeamAdd20Filled,
  PeopleTeamAdd20Regular,
  Person20Filled,
  Person20Regular,
  PersonBriefcase20Filled,
  PersonBriefcase20Regular,
  PersonShield20Filled,
  PersonShield20Regular,
  Phone20Filled,
  Phone20Regular,
  Pill20Filled,
  Pill20Regular,
  Pin20Filled,
  Pin20Regular,
  Pipeline20Filled,
  Pipeline20Regular,
  Planet20Filled,
  Planet20Regular,
  PlugConnected20Filled,
  PlugConnected20Regular,
  Predictions20Filled,
  Predictions20Regular,
  Premium20Filled,
  Premium20Regular,
  Production20Filled,
  Production20Regular,
  PuzzlePiece20Filled,
  PuzzlePiece20Regular,
  QuestionCircle20Filled,
  QuestionCircle20Regular,
  Radar20Filled,
  Radar20Regular,
  Receipt20Filled,
  Receipt20Regular,
  Ribbon20Filled,
  Ribbon20Regular,
  Road20Filled,
  Road20Regular,
  Rocket20Filled,
  Rocket20Regular,
  Scales20Filled,
  Scales20Regular,
  Scan20Filled,
  Scan20Regular,
  ScanTable20Filled,
  ScanTable20Regular,
  Search20Filled,
  Search20Regular,
  SearchShield20Filled,
  SearchShield20Regular,
  Server20Filled,
  Server20Regular,
  Settings20Filled,
  Settings20Regular,
  Share20Filled,
  Share20Regular,
  Shield20Filled,
  Shield20Regular,
  ShieldCheckmark20Filled,
  ShieldCheckmark20Regular,
  Signature20Filled,
  Signature20Regular,
  SlideMultiple20Filled,
  SlideMultiple20Regular,
  Sparkle20Filled,
  Sparkle20Regular,
  SparkleCircle20Filled,
  SparkleCircle20Regular,
  Stack20Filled,
  Stack20Regular,
  Star20Filled,
  Star20Regular,
  Stethoscope20Filled,
  Stethoscope20Regular,
  Storage20Filled,
  Storage20Regular,
  Syringe20Filled,
  Syringe20Regular,
  Table20Filled,
  Table20Regular,
  Tag20Filled,
  Tag20Regular,
  Target20Filled,
  Target20Regular,
  TaskListSquareSettings20Filled,
  TaskListSquareSettings20Regular,
  Teaching20Filled,
  Teaching20Regular,
  Temperature20Filled,
  Temperature20Regular,
  Timeline20Filled,
  Timeline20Regular,
  Toolbox20Filled,
  Toolbox20Regular,
  Trophy20Filled,
  Trophy20Regular,
  Vault20Filled,
  Vault20Regular,
  VehicleTruck20Filled,
  VehicleTruck20Regular,
  Video20Filled,
  Video20Regular,
  Warning20Filled,
  Warning20Regular,
  Window20Filled,
  Window20Regular,
  Wrench20Filled,
  Wrench20Regular,
  WrenchScrewdriver20Filled,
  WrenchScrewdriver20Regular,
  Xray20Filled,
  Xray20Regular,
  bundleIcon,
  type FluentIcon,
} from "@fluentui/react-icons";

export interface WorkspaceIconOption {
  name: string;
  label: string;
  Icon: FluentIcon;
  aliases?: string[];
  keywords?: string[];
}

function option(
  name: string,
  label: string,
  filledIcon: FluentIcon,
  regularIcon: FluentIcon,
  aliases: string[] = [],
  keywords: string[] = [],
): WorkspaceIconOption {
  return {
    name,
    label,
    Icon: bundleIcon(filledIcon, regularIcon),
    ...(aliases.length ? { aliases } : {}),
    ...(keywords.length ? { keywords } : {}),
  };
}

export const workspaceIconOptions: WorkspaceIconOption[] = [
  option("folder", "Folder", FolderOpen20Filled, FolderOpen20Regular, [], ["directory", "files", "drive"]),
  option("briefcase", "Briefcase", Briefcase20Filled, Briefcase20Regular, [], ["business", "client", "project", "work"]),
  option("notebook", "Notebook", Notebook20Filled, Notebook20Regular, [], ["notes", "journal", "workspace"]),
  option("messages", "Messages", ChatMultiple20Filled, ChatMultiple20Regular, [], ["chat", "conversation", "discussion"]),
  option("files", "Files", DocumentMultiple20Filled, DocumentMultiple20Regular, [], ["documents", "papers", "collection"]),
  option("archive", "Archive", Archive20Filled, Archive20Regular, ["archive-restore"], ["records", "stored", "retention"]),
  option("archive-multiple", "Archive multiple", ArchiveMultiple20Filled, ArchiveMultiple20Regular, [], ["records", "vault", "boxes"]),
  option("layers", "Layers", Stack20Filled, Stack20Regular, [], ["stack", "program", "portfolio"]),
  option("workflow", "Workflow", Flow20Filled, Flow20Regular, [], ["process", "flow", "automation"]),
  option("flowchart", "Flowchart", Flowchart20Filled, Flowchart20Regular, [], ["process", "diagram", "mapping"]),
  option("branch", "Branch", Branch20Filled, Branch20Regular, ["git-branch", "git-merge"], ["version", "merge", "fork"]),
  option("branch-compare", "Branch compare", BranchCompare20Filled, BranchCompare20Regular, [], ["compare", "change", "version"]),
  option("target", "Target", Target20Filled, Target20Regular, [], ["goal", "objective", "milestone"]),
  option("flag", "Flag", Flag20Filled, Flag20Regular, [], ["marker", "priority", "milestone"]),
  option("shield", "Shield", Shield20Filled, Shield20Regular, ["shield-plus"], ["security", "protected", "policy"]),
  option("shield-check", "Shield check", ShieldCheckmark20Filled, ShieldCheckmark20Regular, [], ["compliant", "validated", "approved"]),
  option("search-shield", "Search shield", SearchShield20Filled, SearchShield20Regular, [], ["audit", "review", "policy"]),
  option("badge", "Badge", Badge20Filled, Badge20Regular, [], ["credential", "verified", "quality"]),
  option("lock", "Lock", LockClosed20Filled, LockClosed20Regular, [], ["secure", "restricted", "private"]),
  option("key", "Key", Key20Filled, Key20Regular, [], ["access", "credential", "secret"]),
  option("vault", "Vault", Vault20Filled, Vault20Regular, [], ["secure", "records", "archive"]),
  option("checklist", "Checklist", ClipboardCheckmark20Filled, ClipboardCheckmark20Regular, ["clipboard"], ["tasks", "review", "approval"]),
  option("tasks", "Task list", ClipboardTask20Filled, ClipboardTask20Regular, ["clipboard-list", "clipboard-pen"], ["todo", "action", "worklist"]),
  option("task-settings", "Task settings", TaskListSquareSettings20Filled, TaskListSquareSettings20Regular, [], ["controls", "procedure", "configuration"]),
  option("approvals", "Approvals", ApprovalsApp20Filled, ApprovalsApp20Regular, [], ["review", "signoff", "approval"]),
  option("checkmark", "Checkmark", CheckmarkCircle20Filled, CheckmarkCircle20Regular, [], ["done", "accepted", "complete"]),
  option("database", "Database", Database20Filled, Database20Regular, [], ["data", "repository", "records"]),
  option("database-search", "Database search", DatabaseSearch20Filled, DatabaseSearch20Regular, [], ["data", "query", "review"]),
  option("storage", "Storage", Storage20Filled, Storage20Regular, [], ["disk", "repository", "records"]),
  option("package", "Package", Box20Filled, Box20Regular, ["container"], ["kit", "bundle", "box"]),
  option("package-check", "Package check", BoxCheckmark20Filled, BoxCheckmark20Regular, ["package-check"], ["kit", "approved", "release"]),
  option("boxes", "Boxes", Cube20Filled, Cube20Regular, [], ["inventory", "assets", "modules"]),
  option("box-multiple", "Box multiple", BoxMultiple20Filled, BoxMultiple20Regular, [], ["inventory", "packages", "kits"]),
  option("building", "Building", Building20Filled, Building20Regular, ["landmark", "school", "hospital"], ["site", "facility", "company"]),
  option("building-bank", "Bank", BuildingBank20Filled, BuildingBank20Regular, [], ["finance", "institution", "regulated"]),
  option("building-government", "Government", BuildingGovernment20Filled, BuildingGovernment20Regular, [], ["agency", "regulator", "authority"]),
  option("building-multiple", "Buildings", BuildingMultiple20Filled, BuildingMultiple20Regular, [], ["sites", "facilities", "locations"]),
  option("factory", "Factory", BuildingFactory20Filled, BuildingFactory20Regular, ["warehouse"], ["manufacturing", "plant", "production"]),
  option("city", "City", City20Filled, City20Regular, [], ["campus", "location", "site"]),
  option("home", "Home", Home20Filled, Home20Regular, [], ["local", "base", "office"]),
  option("earth", "Earth", Earth20Filled, Earth20Regular, [], ["global", "world", "environment"]),
  option("globe", "Globe", Globe20Filled, Globe20Regular, ["map", "compass", "plane", "ship", "truck", "satellite"], ["global", "web", "world"]),
  option("map", "Map", Map20Filled, Map20Regular, [], ["location", "route", "site"]),
  option("location", "Location", Location20Filled, Location20Regular, [], ["pin", "site", "place"]),
  option("navigation", "Navigation", Navigation20Filled, Navigation20Regular, [], ["route", "compass", "direction"]),
  option("compass", "Compass", CompassNorthwest20Filled, CompassNorthwest20Regular, [], ["direction", "navigation", "guide"]),
  option("road", "Road", Road20Filled, Road20Regular, [], ["route", "travel", "path"]),
  option("truck", "Truck", VehicleTruck20Filled, VehicleTruck20Regular, [], ["delivery", "shipping", "logistics"]),
  option("airplane", "Airplane", Airplane20Filled, Airplane20Regular, [], ["travel", "transport", "flight"]),
  option("people", "People", People20Filled, People20Regular, ["users", "contact"], ["team", "users", "staff"]),
  option("people-team", "Team", PeopleTeam20Filled, PeopleTeam20Regular, [], ["group", "department", "staff"]),
  option("people-add", "Team add", PeopleTeamAdd20Filled, PeopleTeamAdd20Regular, [], ["onboard", "invite", "users"]),
  option("community", "Community", PeopleCommunity20Filled, PeopleCommunity20Regular, [], ["group", "stakeholders", "network"]),
  option("person", "Person", Person20Filled, Person20Regular, [], ["user", "owner", "assignee"]),
  option("person-briefcase", "Person briefcase", PersonBriefcase20Filled, PersonBriefcase20Regular, [], ["client", "owner", "business"]),
  option("person-shield", "Person shield", PersonShield20Filled, PersonShield20Regular, [], ["security", "qualified", "reviewer"]),
  option("contact-card", "Contact card", ContactCard20Filled, ContactCard20Regular, [], ["profile", "identity", "person"]),
  option("handshake", "Handshake", Handshake20Filled, Handshake20Regular, [], ["partner", "agreement", "client"]),
  option("accessibility", "Accessibility", Accessibility20Filled, Accessibility20Regular, [], ["inclusive", "access", "support"]),
  option("book", "Book", BookOpen20Filled, BookOpen20Regular, ["book-marked", "scroll", "graduation"], ["guide", "manual", "knowledge"]),
  option("book-search", "Book search", BookSearch20Filled, BookSearch20Regular, [], ["research", "reference", "lookup"]),
  option("book-database", "Book database", BookDatabase20Filled, BookDatabase20Regular, [], ["knowledge", "records", "reference"]),
  option("library", "Library", Library20Filled, Library20Regular, [], ["knowledge", "catalog", "reference"]),
  option("bookmark", "Bookmark", Bookmark20Filled, Bookmark20Regular, [], ["saved", "favorite", "reference"]),
  option("teaching", "Teaching", Teaching20Filled, Teaching20Regular, [], ["training", "learning", "education"]),
  option("scale", "Scale", Scales20Filled, Scales20Regular, [], ["legal", "balanced", "justice"]),
  option("gavel", "Gavel", Gavel20Filled, Gavel20Regular, [], ["legal", "decision", "authority"]),
  option("money", "Money", Money20Filled, Money20Regular, ["banknote", "dollar"], ["finance", "budget", "cost"]),
  option("receipt", "Receipt", Receipt20Filled, Receipt20Regular, [], ["invoice", "expense", "billing"]),
  option("gift", "Gift", Gift20Filled, Gift20Regular, [], ["reward", "benefit", "offer"]),
  option("certificate", "Certificate", Certificate20Filled, Certificate20Regular, ["gem", "medal"], ["credential", "license", "qualification"]),
  option("ribbon", "Ribbon", Ribbon20Filled, Ribbon20Regular, [], ["award", "certified", "quality"]),
  option("crown", "Crown", Crown20Filled, Crown20Regular, ["crown"], ["premium", "leader", "executive"]),
  option("trophy", "Trophy", Trophy20Filled, Trophy20Regular, [], ["award", "success", "achievement"]),
  option("star", "Star", Star20Filled, Star20Regular, [], ["favorite", "priority", "quality"]),
  option("premium", "Premium", Premium20Filled, Premium20Regular, [], ["special", "quality", "favorite"]),
  option("sparkles", "Sparkles", Sparkle20Filled, Sparkle20Regular, ["zap"], ["magic", "ai", "new"]),
  option("sparkle-circle", "Sparkle circle", SparkleCircle20Filled, SparkleCircle20Regular, [], ["ai", "highlight", "special"]),
  option("flash", "Flash", Flash20Filled, Flash20Regular, [], ["fast", "energy", "lightning"]),
  option("lightbulb", "Lightbulb", Lightbulb20Filled, Lightbulb20Regular, [], ["idea", "insight", "innovation"]),
  option("bot", "Bot", Bot20Filled, Bot20Regular, [], ["agent", "ai", "automation"]),
  option("bot-sparkle", "Bot sparkle", BotSparkle20Filled, BotSparkle20Regular, [], ["agent", "ai", "assistant"]),
  option("agents", "Agents", Agents20Filled, Agents20Regular, [], ["ai", "assistant", "automation"]),
  option("brain", "Brain", Brain20Filled, Brain20Regular, [], ["thinking", "knowledge", "analysis"]),
  option("brain-circuit", "Brain circuit", BrainCircuit20Filled, BrainCircuit20Regular, [], ["ai", "machine learning", "analysis"]),
  option("predictions", "Predictions", Predictions20Filled, Predictions20Regular, [], ["forecast", "model", "analysis"]),
  option("developer-board", "Developer board", DeveloperBoard20Filled, DeveloperBoard20Regular, [], ["hardware", "device", "embedded"]),
  option("code", "Code", Code20Filled, Code20Regular, [], ["software", "developer", "script"]),
  option("server", "Server", Server20Filled, Server20Regular, [], ["backend", "infrastructure", "system"]),
  option("cloud", "Cloud", Cloud20Filled, Cloud20Regular, [], ["online", "remote", "hosted"]),
  option("cloud-database", "Cloud database", CloudDatabase20Filled, CloudDatabase20Regular, [], ["data", "hosted", "repository"]),
  option("cloud-flow", "Cloud flow", CloudFlow20Filled, CloudFlow20Regular, [], ["automation", "workflow", "online"]),
  option("plug", "Plug connected", PlugConnected20Filled, PlugConnected20Regular, [], ["integration", "connected", "power"]),
  option("pipeline", "Pipeline", Pipeline20Filled, Pipeline20Regular, [], ["build", "process", "flow"]),
  option("window", "Window", Window20Filled, Window20Regular, [], ["app", "screen", "desktop"]),
  option("desktop", "Desktop", Desktop20Filled, Desktop20Regular, ["panel"], ["computer", "screen", "windows"]),
  option("laptop", "Laptop", Laptop20Filled, Laptop20Regular, [], ["computer", "portable", "device"]),
  option("phone", "Phone", Phone20Filled, Phone20Regular, [], ["mobile", "call", "device"]),
  option("video", "Video", Video20Filled, Video20Regular, [], ["media", "recording", "meeting"]),
  option("camera", "Camera", Camera20Filled, Camera20Regular, [], ["photo", "image", "capture"]),
  option("image", "Image", Image20Filled, Image20Regular, [], ["picture", "photo", "visual"]),
  option("slide", "Slides", SlideMultiple20Filled, SlideMultiple20Regular, [], ["presentation", "deck", "powerpoint"]),
  option("table", "Table", Table20Filled, Table20Regular, [], ["spreadsheet", "grid", "matrix"]),
  option("document", "Document", Document20Filled, Document20Regular, [], ["file", "paper", "text"]),
  option("document-text", "Document text", DocumentText20Filled, DocumentText20Regular, [], ["file", "text", "report"]),
  option("document-word", "Word document", DocumentWord20Filled, DocumentWord20Regular, [], ["docx", "office", "procedure"]),
  option("document-pdf", "PDF document", DocumentPdf20Filled, DocumentPdf20Regular, [], ["pdf", "controlled", "source"]),
  option("document-table", "Document table", DocumentTable20Filled, DocumentTable20Regular, [], ["spreadsheet", "matrix", "data"]),
  option("document-data", "Document data", DocumentData20Filled, DocumentData20Regular, [], ["analytics", "report", "dataset"]),
  option("document-check", "Document check", DocumentCheckmark20Filled, DocumentCheckmark20Regular, [], ["approved", "validated", "complete"]),
  option("document-search", "Document search", DocumentSearch20Filled, DocumentSearch20Regular, [], ["review", "audit", "lookup"]),
  option("document-edit", "Document edit", DocumentEdit20Filled, DocumentEdit20Regular, [], ["draft", "author", "write"]),
  option("document-signature", "Signature document", DocumentSignature20Filled, DocumentSignature20Regular, [], ["signed", "approval", "controlled"]),
  option("document-ribbon", "Certified document", DocumentRibbon20Filled, DocumentRibbon20Regular, [], ["certificate", "quality", "approved"]),
  option("document-briefcase", "Business document", DocumentBriefcase20Filled, DocumentBriefcase20Regular, [], ["client", "project", "work"]),
  option("source-folder", "Source folder", DocumentFolder20Filled, DocumentFolder20Regular, [], ["files", "folder", "documents"]),
  option("folder-document", "Folder document", FolderDocument20Filled, FolderDocument20Regular, [], ["docs", "records", "files"]),
  option("folder-briefcase", "Folder briefcase", FolderBriefcase20Filled, FolderBriefcase20Regular, [], ["project", "client", "business"]),
  option("folder-data", "Folder data", FolderDataBar20Filled, FolderDataBar20Regular, [], ["analytics", "metrics", "reports"]),
  option("folder-globe", "Folder globe", FolderGlobe20Filled, FolderGlobe20Regular, [], ["global", "web", "shared"]),
  option("folder-multiple", "Folders", FolderMultiple20Filled, FolderMultiple20Regular, [], ["many", "collection", "files"]),
  option("folder-search", "Folder search", FolderSearch20Filled, FolderSearch20Regular, [], ["review", "lookup", "audit"]),
  option("folder-sync", "Folder sync", FolderSync20Filled, FolderSync20Regular, [], ["cloud", "mirror", "refresh"]),
  option("drawer", "Drawer", Drawer20Filled, Drawer20Regular, [], ["inbox", "records", "storage"]),
  option("notepad", "Notepad", Notepad20Filled, Notepad20Regular, [], ["notes", "memo", "scratch"]),
  option("board", "Board", Board20Filled, Board20Regular, [], ["planning", "kanban", "whiteboard"]),
  option("form", "Forms", FormMultiple20Filled, FormMultiple20Regular, [], ["survey", "intake", "questionnaire"]),
  option("mail", "Mail", Mail20Filled, Mail20Regular, [], ["email", "message", "inbox"]),
  option("comment", "Comments", CommentMultiple20Filled, CommentMultiple20Regular, [], ["feedback", "discussion", "review"]),
  option("chat-check", "Chat check", ChatCheckmark20Filled, ChatCheckmark20Regular, [], ["approved", "conversation", "support"]),
  option("chat-question", "Question chat", ChatBubblesQuestion20Filled, ChatBubblesQuestion20Regular, [], ["help", "support", "q&a"]),
  option("question", "Question", QuestionCircle20Filled, QuestionCircle20Regular, [], ["help", "unknown", "support"]),
  option("info", "Info", Info20Filled, Info20Regular, [], ["details", "about", "reference"]),
  option("news", "News", News20Filled, News20Regular, [], ["updates", "announcements", "feed"]),
  option("calendar", "Calendar", Calendar20Filled, Calendar20Regular, [], ["schedule", "date", "plan"]),
  option("calendar-check", "Calendar check", CalendarCheckmark20Filled, CalendarCheckmark20Regular, [], ["schedule", "complete", "due date"]),
  option("clock", "Clock", Clock20Filled, Clock20Regular, [], ["time", "deadline", "schedule"]),
  option("access-time", "Access time", AccessTime20Filled, AccessTime20Regular, [], ["time", "history", "recent"]),
  option("history", "History", History20Filled, History20Regular, [], ["past", "audit trail", "recent"]),
  option("timeline", "Timeline", Timeline20Filled, Timeline20Regular, [], ["history", "schedule", "sequence"]),
  option("chart", "Charts", ChartMultiple20Filled, ChartMultiple20Regular, [], ["analytics", "metrics", "graphs"]),
  option("data-pie", "Data pie", DataPie20Filled, DataPie20Regular, [], ["analytics", "chart", "metrics"]),
  option("data-trending", "Data trending", DataTrending20Filled, DataTrending20Regular, [], ["analytics", "trend", "performance"]),
  option("clipboard-data", "Clipboard data", ClipboardDataBar20Filled, ClipboardDataBar20Regular, [], ["metrics", "report", "assessment"]),
  option("gauge", "Gauge", Gauge20Filled, Gauge20Regular, ["radar"], ["dashboard", "metric", "performance"]),
  option("radar", "Radar", Radar20Filled, Radar20Regular, [], ["monitor", "scan", "signal"]),
  option("scan", "Scan", Scan20Filled, Scan20Regular, ["scan", "search-check"], ["inspect", "review", "capture"]),
  option("scan-table", "Scan table", ScanTable20Filled, ScanTable20Regular, [], ["inspect", "spreadsheet", "review"]),
  option("barcode", "Barcode scanner", BarcodeScanner20Filled, BarcodeScanner20Regular, [], ["scan", "inventory", "device"]),
  option("filter", "Filter", Filter20Filled, Filter20Regular, [], ["funnel", "sort", "narrow"]),
  option("search", "Search", Search20Filled, Search20Regular, [], ["lookup", "find", "review"]),
  option("eye", "Eye", Eye20Filled, Eye20Regular, [], ["view", "inspect", "visibility"]),
  option("edit", "Edit", Edit20Filled, Edit20Regular, [], ["pencil", "author", "change"]),
  option("pen", "Pen", Pen20Filled, Pen20Regular, [], ["write", "sign", "author"]),
  option("signature", "Signature", Signature20Filled, Signature20Regular, [], ["signoff", "approval", "signed"]),
  option("tag", "Tag", Tag20Filled, Tag20Regular, [], ["label", "category", "metadata"]),
  option("pin", "Pin", Pin20Filled, Pin20Regular, [], ["location", "fixed", "important"]),
  option("attach", "Attach", Attach20Filled, Attach20Regular, [], ["attachment", "link", "file"]),
  option("share", "Share", Share20Filled, Share20Regular, [], ["send", "collaborate", "export"]),
  option("sync", "Sync", ArrowSync20Filled, ArrowSync20Regular, [], ["refresh", "mirror", "update"]),
  option("settings", "Settings", Settings20Filled, Settings20Regular, ["cpu", "network", "activity"], ["configure", "preferences", "controls"]),
  option("toolbox", "Toolbox", Toolbox20Filled, Toolbox20Regular, [], ["tools", "utility", "work"]),
  option("wrench", "Wrench", Wrench20Filled, Wrench20Regular, ["hammer"], ["maintenance", "tools", "fix"]),
  option("wrench-screwdriver", "Wrench screwdriver", WrenchScrewdriver20Filled, WrenchScrewdriver20Regular, [], ["tools", "service", "repair"]),
  option("puzzle", "Puzzle", PuzzlePiece20Filled, PuzzlePiece20Regular, [], ["extension", "integration", "plugin"]),
  option("apps", "Apps", Apps20Filled, Apps20Regular, [], ["applications", "tools", "tiles"]),
  option("app-list", "App list", AppsListDetail20Filled, AppsListDetail20Regular, [], ["catalog", "tools", "list"]),
  option("panel", "Panel", PanelLeft20Filled, PanelLeft20Regular, [], ["sidebar", "layout", "navigation"]),
  option("more", "More", MoreHorizontal20Filled, MoreHorizontal20Regular, [], ["ellipsis", "options", "misc"]),
  option("diagram", "Diagram", Diagram20Filled, Diagram20Regular, [], ["architecture", "map", "visual"]),
  option("layer", "Layer", Layer20Filled, Layer20Regular, [], ["layers", "stack", "design"]),
  option("classification", "Classification", Classification20Filled, Classification20Regular, [], ["controlled", "label", "sensitive"]),
  option("warning", "Warning", Warning20Filled, Warning20Regular, [], ["risk", "alert", "issue"]),
  option("alert", "Alert", Alert20Filled, Alert20Regular, [], ["warning", "notification", "risk"]),
  option("heart", "Heart", Heart20Filled, Heart20Regular, [], ["care", "health", "favorite"]),
  option("doctor", "Doctor", Doctor20Filled, Doctor20Regular, [], ["medical", "clinical", "health"]),
  option("patient", "Patient", Patient20Filled, Patient20Regular, [], ["medical", "clinical", "health"]),
  option("stethoscope", "Stethoscope", Stethoscope20Filled, Stethoscope20Regular, [], ["medical", "clinical", "health"]),
  option("pill", "Pill", Pill20Filled, Pill20Regular, [], ["pharma", "medicine", "drug"]),
  option("syringe", "Syringe", Syringe20Filled, Syringe20Regular, [], ["medical", "device", "injection"]),
  option("xray", "X-ray", Xray20Filled, Xray20Regular, [], ["medical", "imaging", "device"]),
  option("beaker", "Beaker", Beaker20Filled, Beaker20Regular, ["flask", "atom", "dna"], ["lab", "science", "test"]),
  option("microscope", "Microscope", Microscope20Filled, Microscope20Regular, ["microscope"], ["lab", "science", "research"]),
  option("temperature", "Temperature", Temperature20Filled, Temperature20Regular, [], ["environment", "cold chain", "monitoring"]),
  option("planet", "Planet", Planet20Filled, Planet20Regular, [], ["science", "space", "global"]),
  option("production", "Production", Production20Filled, Production20Regular, [], ["manufacturing", "release", "build"]),
  option("rocket", "Rocket", Rocket20Filled, Rocket20Regular, [], ["launch", "release", "startup"]),
  option("backpack", "Backpack", Backpack20Filled, Backpack20Regular, [], ["travel", "field", "kit"]),
  option("desk", "Desk", Desk20Filled, Desk20Regular, [], ["office", "workspace", "work"]),
];

const workspaceIconLookup = new Map<string, WorkspaceIconOption>();

for (const iconOption of workspaceIconOptions) {
  workspaceIconLookup.set(iconOption.name, iconOption);
  for (const alias of iconOption.aliases ?? []) {
    workspaceIconLookup.set(alias, iconOption);
  }
}

export function workspaceIconOptionFor(iconName: string | null | undefined): WorkspaceIconOption {
  const normalizedIconName = iconName?.trim().toLowerCase();
  return normalizedIconName ? workspaceIconLookup.get(normalizedIconName) ?? workspaceIconOptions[0] : workspaceIconOptions[0];
}

export function filterWorkspaceIconOptions(query: string): WorkspaceIconOption[] {
  const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!tokens.length) return workspaceIconOptions;
  return workspaceIconOptions
    .map((iconOption, index) => ({ iconOption, index, score: workspaceIconSearchScore(iconOption, tokens) }))
    .filter((result) => Number.isFinite(result.score))
    .sort((left, right) => left.score - right.score || left.index - right.index)
    .map((result) => result.iconOption);
}

function workspaceIconSearchScore(iconOption: WorkspaceIconOption, tokens: string[]): number {
  const values = [iconOption.name, iconOption.label, ...(iconOption.aliases ?? []), ...(iconOption.keywords ?? [])].map((value) => value.toLowerCase());
  const words = values.flatMap((value) => value.split(/[^a-z0-9]+/).filter(Boolean));
  let score = 0;
  for (const token of tokens) {
    const tokenScore = workspaceIconTokenScore(token, values, words);
    if (!Number.isFinite(tokenScore)) return Number.POSITIVE_INFINITY;
    score += tokenScore;
  }
  return score;
}

function workspaceIconTokenScore(token: string, values: string[], words: string[]): number {
  if (values.some((value) => value === token) || words.some((word) => word === token)) return 0;
  if (values.some((value) => value.startsWith(token)) || words.some((word) => word.startsWith(token))) return 1;
  if (values.some((value) => value.includes(token))) return 2;
  return Number.POSITIVE_INFINITY;
}
